[package]
name = "planner"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0"
env_logger = "0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
priority-queue = "2"
bresenham = "0"
clap = { version = "4", features = ["derive"] }
